package com.company;

public class Main {

    public static void main(String[] args) {

        /*
         Note no. 1: Adding string together to allow for multi-line strings,
         making the picture easier to see from the editor.

         Note no. 2: This tree was generated by a python/javascript
         program I wrote more than a year ago. You can find it here:
         https://github.com/liam-ilan/forest-generation-cellular-automata.

         Note no. 3: color escape codes used. Hopefully will work if you are using this.

         Note no. 4: \u001b[31mo\u001b[32m = apple
        */

        // output
        System.out.print("\u001b[32m                              x" + // green
                "\n                     x  xxxxxxxxx" +
                "\n                   xxxxxxxxxxx\u001b[31mo\u001b[32mxx  xxxxx" +
                "\n                       x xx  xxxxxxxxxxxxx" +
                "\n                  xxxxxxx\u001b[31mo\u001b[32mxxxxxxxxxxxxxxxxxxxxx" +
                "\n                  xxxxxx   x  xx xxxxxx     xxx\u001b[31mo\u001b[32mxxx" +
                "\n            xxxxx   xxxxx xxxxxxxxxxxxxxxxxxxxxxxx" +
                "\n     xx        xxxx  xxx\u001b[31mo\u001b[32mxxxxxxx xx    xxxxxxxxxxxx" +
                "\n     xxxxxxxxxxxxxxx   xxx   xxxxxx  xxxx" +
                "\n      xxxxxxxxxx\u001b[31mo\u001b[32mxxxxxxxxxx\u001b[31mo\u001b[32mxxx  xxxxxxx" +
                "\n       xxxxxxxxxxxxxxxxxxxxxx\u001b[31mo\u001b[32mxx xx" +
                "\n                xxxxxxx\u001b[31mo\u001b[32mxxxxxx xxxxxx" +
                "\n                         x xxxxxxxxx" +
                "\n                        xxxxxxxxx" +
                "\n                        xxx\u001b[31mo\u001b[32mxxx" +
                "\n                          x  xx" +
                "\n                          xxxxxx" +
                "\n\u001b[0m                             xx" + // white
                "\n                              x" +
                "\n                              x" +
                "\n                              x");
    }
}
